#server:
#  port: 8081
spring:


  main:
    banner-mode: off
    log-startup-info: false
    lazy-initialization: true

  sql:
    init:
      continue-on-error: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 11031999

    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        "[format_sql]": true
        "[generate_statistics]": true
        
  thymeleaf:
    cache: false